export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'

export const EMPLOYER_CREATE_REQUEST = 'EMPLOYER_CREATE_REQUEST'
export const EMPLOYER_CREATE_SUCCESS = 'EMPLOYER_CREATE_SUCCESS'
export const EMPLOYER_CREATE_FAIL = 'EMPLOYER_CREATE_FAIL'
export const EMPLOYER_CREATE_RESET = 'EMPLOYER_CREATE_RESET'